# Execute subunit2html and collects results from a tempest run
# mostly geared towards grabbing everything required by 3'rd party
# CI results reporting.
#
#   Parameters:
#   - `hosts` = lists of hosts to run playbook against
#   - `upload_script` = script to bundle everything up (it's just easier than
#      trying to it in the playbook)
#   - `instance_name` = handy name for a local subdir to store results in
#   - `results_dir` = local directory to fetch stack.sh results to
#
#   Example:
#   `ansible-playbook run_cleanup.yml --extra-vars="hosts=192.168.1.9, \
#   upload_script=myscript.sh instance_name=WildBill results_dir=some-local-dir" -i 192.168.1.9,
#
#   ** NOTE: For CI we typicaly use the patchset ref: refs/changes/02/291302/2
#            and just s/\//-/


- hosts: "{{ hosts }}"
  tasks:

  - name: send over upload script
    sudo: no
    template: src={{ upload_script }} dest=/home/ubuntu/

  - name: send over subunit2html script
    sudo: no
    template: src=../../scripts/subunit2html.py dest=/opt/stack/tempest/

  - name: Verify permissions on subunit2html
    sudo: no
    shell: chmod 755 subunit2html.py
    args:
      chdir: /opt/stack/tempest

  - name: Generate subunit.log
    sudo: no
    shell: testr last --subunit > testrepository.subunit
    args:
      chdir: /opt/stack/tempest

  - name: Generate results.html
    sudo: no
    shell: ./subunit2html.py testrepository.subunit
    args:
      chdir: /opt/stack/tempest


  - name: run upload
    sudo: yes
    shell: bash {{ upload_script }} {{ instance_name }}
    args:
      chdir: /home/ubuntu

  - name: fetch tempest_results
    sudo: yes
    fetch: src=/opt/stack/tempest/console.log.out dest="{{ results_dir }}"/"{{ instance_name }}"/console.log.out flat=yes validate_md5=no

  - name: fetch testr_results.html
    sudo: yes
    fetch: src=/opt/stack/tempest/results.html dest="{{ results_dir }}"/"{{ instance_name }}"/testr_results.html flat=yes validate_md5=no

  - name: fetch testrepository.subunit
    sudo: yes
    fetch: src=/opt/stack/tempest/testrepository.subunit dest="{{ results_dir }}"/"{{ instance_name }}"/testrepository.subunit flat=yes validate_md5=no

  - name: fetch logs
    sudo: yes
    fetch: src=/home/ubuntu/"{{instance_name}}"/"{{ instance_name }}".tar.gz dest="{{ results_dir }}"/ flat=yes validate_md5=no
